export function createElements() {
  return {
    dropzone: document.getElementById("dropzone"),
    fileInput: document.getElementById("fileInput"),
    languageSelect: document.getElementById("languageSelect"),
    pdfQualitySelect: document.getElementById("pdfQualitySelect"),
    psmSelect: document.getElementById("psmSelect"),
    preprocessSelect: document.getElementById("preprocessSelect"),
    upscaleSelect: document.getElementById("upscaleSelect"),
    dictionarySelect: document.getElementById("dictionarySelect"),
    charModeSelect: document.getElementById("charModeSelect"),
    pageRangeModal: document.getElementById("pageRangeModal"),
    pageRangePanel: document.getElementById("pageRangePanel"),
    pageRangeTitle: document.getElementById("pageRangeTitle"),
    pageRangeMessage: document.getElementById("pageRangeMessage"),
    pdfRangeList: document.getElementById("pdfRangeList"),
    pageRangeProcessBtn: document.getElementById("pageRangeProcessBtn"),
    autoRotateInput: document.getElementById("autoRotateInput"),
    borderPaddingInput: document.getElementById("borderPaddingInput"),
    forceOcrInput: document.getElementById("forceOcrInput"),
    preserveSpacesInput: document.getElementById("preserveSpacesInput"),
    progressBar: document.getElementById("progressBar"),
    statusLine: document.getElementById("statusLine"),
    summaryLine: document.getElementById("summaryLine"),
    fieldGrid: document.getElementById("fieldGrid"),
    textOutput: document.getElementById("textOutput"),
    fileList: document.getElementById("fileList"),
    pageList: document.getElementById("pageList"),
    copyTextBtn: document.getElementById("copyTextBtn"),
    downloadTxtBtn: document.getElementById("downloadTxtBtn"),
    downloadPdfBtn: document.getElementById("downloadPdfBtn"),
    downloadRawJsonBtn: document.getElementById("downloadRawJsonBtn"),
    cancelBtn: document.getElementById("cancelBtn"),
    selectFieldsBtn: document.getElementById("selectFieldsBtn"),
    clearFieldsBtn: document.getElementById("clearFieldsBtn"),
    copyStructuredBtn: document.getElementById("copyStructuredBtn"),
    downloadStructuredTxtBtn: document.getElementById("downloadStructuredTxtBtn"),
    downloadStructuredJsonBtn: document.getElementById("downloadStructuredJsonBtn"),
    downloadCsvBtn: document.getElementById("downloadCsvBtn"),
    clearBtn: document.getElementById("clearBtn"),
    toast: document.getElementById("toast"),
  };
}

export function createInitialState() {
  return {
    files: [],
    pages: [],
    pdfParts: [],
    pdfSources: [],
    pdfPageCount: 0,
    pdfRangeFiles: [],
    pdfPageRanges: new Map(),
    pdfFilePageCounts: new Map(),
    pendingFiles: [],
    text: "",
    fields: {},
    selectedFields: {},
    fieldSelectionLockedByUser: false,
    busy: false,
    cancelRequested: false,
    currentSession: null,
    sessionId: 0,
    pdfUnavailable: false,
    pdfUnavailableMessage: "",
  };
}
